osr_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  drive_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - joint1
    gains:
      joint1: {p: 5, d: 1, i: 0}