osr_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  drive_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - joint1
      - joint2
    gains:
      joint1: {p: 10, d: 1, i: 0}
      joint2: {p: 10, d: 1, i: 0}
